version: "2"

services:
  zookeeper:
    image: bitnami/zookeeper
    networks:
      - mongodb-network
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka_server
    image: bitnami/kafka
    networks:
      - mongodb-network
    ports:
      - "9092:9092"
      - "8080:8080"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  mongodb-network:
    driver: bridge